### ISSUE TITLE
繁體系統亂碼

### ISSUE THREAD

**Issue by Small-Ku** [Scighost/StarRailTool#3]
![圖片](https://github.com/Scighost/StarRailTool/assets/16464896/1a39b6ca-c3d4-48d4-bf84-84b38e2b2dff)

**Comment by Scighost** [comment]
尝试过把系统语言改成**简体中文**了吗

**Comment by ksharperd** [comment]
> 

這邊有同樣的問題~

**Comment by Small-Ku** [comment]
> 尝试过把系统语言改成**简体中文**了吗

![圖片](https://github.com/Scighost/StarRailTool/assets/16464896/5feb9d20-36ac-488f-938b-d6c5a0a9017e)

換成簡體問題依然存在

版本	Windows 11 专业版
版本	22H2
操作系统版本	25357.1
体验	Windows Feature Experience Pack 1000.25350.1000.0

**Comment by Small-Ku** [comment]
![圖片](https://github.com/Scighost/StarRailTool/assets/16464896/bad95985-7e36-4b67-ae41-a7be252dd91b)

目前需要開啓這個 Beta 才能不亂碼

**Comment by Scighost** [comment]
本项目不再维护，请移步 https://github.com/Scighost/Starward
